name = "d1files-nuxt"
compatibility_date = "2026-09-01"
pages_build_output_dir = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "d1files-db"
database_id = "tu-database-id-aqui"

[vars]
AUTH_TOKEN = "tu_clave_secreta_aqui"
CUSTOM_ID_TOKEN = "tu_clave_para_ids_propios"
